spring:
  application:
    name: ZipCock_44
  jwt:
    secret: ${SECRET_KEY}
  main:
    debug: true
  profiles:
    active: test
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kakao: # 카카오 로그인 설정
    client: ${CLIENT_ID}
    redirect: ${REDIRECT_URI}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

